version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - 23306:3306
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=password
  redis:
    image: redis:latest
    ports:
      - 26379:6379
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - redis
      - mysql
